### ISSUE TITLE
Push behaviour

### ISSUE THREAD

**Issue by ghost** [ProPra16/programmierpraktikum-abschlussprojekt-zenamike#10]
@ProPra16/team-zenamike 
@ProPra16/zenamike 

Can we please agree on pushing only if the code is compileable? I would also suggest to make only  small retraceable pushes; not such big things nobody understands what you're doing.

**Comment by Wiredaemon** [comment]
suggestion:
create feature branches where you can commit and push as you like.
When a feature is finished, you can issue a team-intern pull request / discuss to merge the finished feature into the master.

Having a master branch that always compiles is a wonderful thing

**Comment by shaman78** [comment]
@Schiggy69  xD

**Comment by ghost** [comment]
Veey funny
Much laugh
Such propra
