### ISSUE TITLE
XMLreader not working 

### ISSUE THREAD

**Issue by zeljkobekcic** [ProPra16/programmierpraktikum-abschlussprojekt-zenamike#11]
@nafoe 
Please fix the xml reader and create some tests.

**Comment by nafoe** [comment]
Got it.

**Comment by zeljkobekcic** [comment]
Issues will be closed when the problem behind the issue has been solved. 

As long as this problem is existing thus issue will remain as unsolved and therefor open and not closed.

**Comment by nafoe** [comment]
*therefore
