### ISSUE TITLE
Finish the GUI

### ISSUE THREAD

**Issue by zeljkobekcic** [ProPra16/programmierpraktikum-abschlussprojekt-zenamike#12]
@shaman78
Please finish the GUI

**Comment by shaman78** [comment]
Please start making sinful comments in you Classes so that i can understand what they are doing
If not , i see no way to implement Babysteps and Tracking into the GUI . 
Sorry it's not my Problem if you don't want to work with me and help me understanding what your 
classes are doing... 

@zeljkobekcic

**Comment by shaman78** [comment]
Example:
    @Override
    public void start() {
        //@TODO finish this
    }

```
@Override
public void stop() {
    //@TODO finish that
}
```

protected void loadSettings() {
        /*
         \* @TODO
         \* 1. Fire rockets
         \* 2. Blame Kim Jong-Un(o)
         \* 2. Use hte XMLReader
         */
are no comments that help me understanding what this code should do xD

**Comment by zeljkobekcic** [comment]
Nimm doch etwas was mit dem Code zutun hat.

Wenn man ploetzlich mit meinen TODO's ankommt, die nur als Troll dienen bzw. als Zeichen dafuer, dass man meine Arbeit  "blockiert" wird, dadurch ,dass eure Arbeit  nicht vorankommt , dann finde ich das ein starkes Stueck. Es ist was anderes wenn man sich nicht die Klassen anschaut, sich nicht die Namen der Klassen anschaut aber trotzdem dann eine Vermutung aufstellt wofuer die Klasse sein koennte, dann tut es mir Leid, wenn du meinen Code nicht verstehst.

**Comment by Wiredaemon** [comment]
Egal ob das Problem durch ein anderes Problem geblockt wird, es bleibt ein Problem und damit offen!

**Comment by shaman78** [comment]
![sub-zero_fatality_mk2](https://cloud.githubusercontent.com/assets/10478748/16857250/f678b030-4a1e-11e6-8bfb-42fb4fc91988.png)

http://vignette3.wikia.nocookie.net/mkwikia/images/f/fe/Sub-Zero_Fatality_MK2.png/revision/latest?cb=20110926135214

Finish the Gui -> Fatality

**Comment by ghost** [comment]
Wat
