### ISSUE TITLE
Please start making sinful comments 

### ISSUE THREAD

**Issue by shaman78** [ProPra16/programmierpraktikum-abschlussprojekt-zenamike#13]
@zeljkobekcic

**Comment by shaman78** [comment]
after this issue is closed you can reopen gui...

**Comment by ghost** [comment]
What does this even mean?

**Comment by nafoe** [comment]
# sinful {adj}

sündhaft [geh.]
sündig
frevelhaft
frevlerisch
frevelhaft [geh.]
freventlich [veraltet]

**Comment by shaman78** [comment]
i mean meaningful sorry
