### ISSUE TITLE
Team-Abstimmung

### ISSUE THREAD

**Issue by Wiredaemon** [ProPra16/programmierpraktikum-abschlussprojekt-zenamike#15]
Hallo,
wie ich sehe gibt es Schwierigkeiten bei der Kommunikation im Team.
Ich mach das ganze einfach mal auf Deutsch, das Englisch ist ja frevelhaft :wink: 

Soweit ich das jetzt verstanden habe möchte @zeljkobekcic den XML Reader verwenden.
Dieser scheint nicht seinem Use-Case entsprechend zu arbeiten.

Wie sieht das Problem aus eurer Situation aus und was ist ein umsetzbarer Fix?

Edit: es scheint nicht nur der XML-reader sondern zusätzlich die GUI zu sein.
Was sind die fehlenden Features?

**Comment by shaman78** [comment]
Das Problem ist das @zeljkobekcic nicht mit den anderen zusammen arbeitet und nur meckert.
Er arbeitet für sich allein und macht hier ständig Issues auf statt mit uns zu reden.

Das grundsätzliche Problem bei der Gui ist das sie vom design fertig ist nur das @zeljkobekcic mir nicht helfen will seine Babystepp und Tracker einzubauen obwohl ich ihm zum 8 mal (wirklich 8 mal!) gesagt habe das ich seinen Code nicht verstehe und nicht weiß wie er das in Verbindung mit dem Cycle etc haben will... Und wenn er einem hilft dann 10min lang dann geht er off und sagt das er für den Tag genug getan hat und hindert mich somit effektiv am weiter arbeiten!

Und das mit dem XML-Reader is so das @zeljkobekcic damit arbeiten müsste er jedoch keine konkreten Anforderungen sonder nur ' mach mal ' sagt und sich dann wundert das es nicht so ist wie er es braucht.

XML-Reader is grade eben auch noch gefixt worden und nur noch offen damit @zeljkobekcic schaut ob es so für ihn passt und es dann selbst schließen kann. 

Gui is halt so das alle Buttons eingebunden etc sind aber noch nicht die Funktionen implementiert wurden , da ich nicht weiß wie das mit den Settings zusammen spielt.

**Comment by shaman78** [comment]
wir reden wieder miteinander :)

**Comment by Wiredaemon** [comment]
Ok.
Wenn ihr alle offenen Fragen intern geklärt habt, würde ich das Issue schließen. Ist das allen recht?

**Comment by shaman78** [comment]
ist allen recht :)
