### ISSUE TITLE
Stand

### ISSUE THREAD

**Issue by Wiredaemon** [ProPra16/programmierpraktikum-abschlussprojekt-zenamike#17]
Seit euch bitte bewusst, dass ich euer Projekt noch einmal getestet habe und zum folgenden Einsicht gekommen bin:

Euer Projekt ist im momemtanen Stand nicht nur extrem buggy, sondern unnutzbar.

Ich habe zuerst angenommen, dass alle Features soweit implementiert sind und durch bugs ich das nicht richtig nutzen kann, aber je mehr ich mir hier ansehe, desto mehr bin ich mir nicht sicher ob das ganze je in irgendeiner form geklappt hat!

Solange ich nicht das Projekt ausführen kann, dann mir zB das Roman numbers kata auswählen kann und mindestens 2 tests schreiben kann und dazu dann eine Implementierung in eurem Programm, ist das ganze **mangelhaft**

Auch dass man babysteps in der gui nicht wirklich anstellen kann heißt, dass das feature effektiv nicht enthalten ist.

Bedenkt, dass bald die Punkte eingetragen werden müssen und auch mir dann die Hände gebunden sind!

**Comment by shaman78** [comment]
Das Problem ist das seit Samstag effektiv außer von @nafoe  und ein wenig von @Schiggy69  keine Hilfe mehr vorhanden ist. (Siehe anderes ISSUE)
Das grundlegende Problem ist grade das der Compiler nicht wirklich compilt und ich nur leere Strings bzw. NULL bekomme wodurch ich nicht verifizieren kann ob der Test bestanden wurde oder nicht, somit kann ich nicht an der Implementierung der anderen Sachen arbeiten, wobei diese eig schon implementiert sein sollten laut @zeljkobekcic .
Zudem werden Babystepp und Tracking laut @zeljkobekcic so wie ich sie gestartet habe "eigentlich" gestartet jedoch gibt es in Babystepp noch keine Möglichkeit die Zeit zu übergeben und bei Tracking habe ich keine Ahnung wie das mit dem extra Fenster funktionieren soll ,da @zeljkobekcic das selber übernehmen wollte ...

**Comment by Wiredaemon** [comment]
Was ich mit babysteps angesprochen habe bezog sich explizit darauf, dass man scheinbar keinen katalog auswählen und gleichzeitig babysteps aktivieren kann in der gui.

Was da hintendrin in dem moment passiert ist mir als user in dem Moment egal.

**Comment by shaman78** [comment]
man müsste aber Babystepp und dann in den Katalog können...

**Comment by zeljkobekcic** [comment]
Moin Chris, also die GUI funktioniert jetzt (halbwegs) dank Jens.

Wir arbeiten jetzt daran, dass die Plugins drinnen sind und dann arbeitet das Teil (hoffentlich) wie gewollt.
Ich stelle einfach mal die Theorie auf das die Plugins funktionieren sollten, da der Code dein Anschein macht.

**Comment by Wiredaemon** [comment]
Alles klar. Werde ich morgen testen

**Comment by zeljkobekcic** [comment]
UPDATE:
Babysteps funktioniert, gerade mit eigenen Augen gesehen. Zeugen vorhanden.

UPDATE10:
Babysteps und Tracker funktionieren gerade. Zeuge vorhanden.

Somit ist nach ein paar Tests das Programm jetzt "benutzbar".
![image](https://cloud.githubusercontent.com/assets/10364991/17059131/0c14efde-5024-11e6-89e1-38f7824ed601.png)

@Wiredaemon
