### ISSUE TITLE
Treffen

### ISSUE THREAD

**Issue by Wiredaemon** [ProPra16/programmierpraktikum-abschlussprojekt-zenamike#4]
Hallo ihr alle.
Ich bin Chris Rutenkolk und für die Gruppenarbeit euer Tutor.

Für nächste Woche müssen wir uns einmal zusammen treffen und ein paar Dinge abklären. Dazu gehört z.B. was ihr bisher gemacht habt, wie euer System aufgebaut ist und wer was in eurem Team macht.

Hier ein doodle zum Termin finden.
Ich habe das Doodle für alle Gruppen freigeschaltet, für die ich zugeteilt bin.
Das ganze habe ich zu eurer Übersicht gemacht.
Achtet also darauf bitte, dass ihr euch nicht an den fremden Team-Mitgliedern orientiert ( ihr wisst ja hoffentlich, wer in eurem Team ist ;) )

http://doodle.com/poll/kqzn7qr8rency3a9

**Comment by Wiredaemon** [comment]
Ich tagge hier einfach mal das ganze Team, dann sollten alle eine Nachricht bekommen ;)
@ProPra16/zenamike

**Comment by zeljkobekcic** [comment]
Habe meine Moeglichen Termine eingetragen. 

Ich tagge mal meine Gruppe damit die sich da auch mal eintragen.
Bzw. die beiden die nicht im Plan drinnen sind.

@nafoe 
@shaman78 

Eintragen in den doodle.com Plan!

**Comment by shaman78** [comment]
@zeljkobekcic 
Alle sind eingetragen und so wie es aussieht ist es Donnerstag 11:30.

**Comment by Wiredaemon** [comment]
Gut. Dann bestimme ich das ganze mal ganz demokratisch auf Donnerstag 11:30 im Rechnerraum (25.12.00.81)

**Comment by Wiredaemon** [comment]
Kleine Plan-Änderung:
Wäre auch Freitag 12:30 oder halt kurz danach bei euch ok?

**Comment by shaman78** [comment]
Wäre nicht möglich da 3 von uns in Info IV sitzen und einer in Japanisch ist.

**Comment by Wiredaemon** [comment]
Alles Klar. Dann bleibts bei Donnerstag 11:30
