### ISSUE TITLE
Suspicious behaviour

### ISSUE THREAD

**Issue by ghost** [ProPra16/programmierpraktikum-abschlussprojekt-zenamike#6]
@Wiredaemon 

![vivaldi_2016-07-08_15-48-20](https://cloud.githubusercontent.com/assets/10684523/16689998/f660c612-4525-11e6-8c75-905efe84b529.png)
![vivaldi_2016-07-08_15-49-05](https://cloud.githubusercontent.com/assets/10684523/16690000/f7ff05ec-4525-11e6-8663-4c11b6e6e6db.png)
![image](https://cloud.githubusercontent.com/assets/10684523/16690143/b7c62d24-4526-11e6-8ef3-6b971b845a5b.png)

Ich habe grade ein bisschen auf git rumgeklickt und beim umsehen habe ich das bemerkt. Ich möchte hier niemanden anschwärzen, wenn es ein Versehen war ist das okay, aber wenn nicht wow.

**Comment by zeljkobekcic** [comment]
![174w7j](https://cloud.githubusercontent.com/assets/10364991/16707535/88422e34-45d2-11e6-9f7f-cab6fef82583.jpg)

**Comment by shaman78** [comment]
ich sag mal so deren projekt besteht aus einem protokol.. ich glaub da müssen wir uns keine sorge machen :D naja is trotzdem komisch ^^

**Comment by Wiredaemon** [comment]
sehr interessant das ganze.
Habs aufm Schirm. Lassen wir erstmal noch offen das Issue. Ist gerade etwas zu spät

**Comment by Wiredaemon** [comment]
Ich hab mir das ganze mal im Detail angesehen und aus dem fork scheint kein Code rübergewandert zu sein.

Also er hat zwar einen Fork erstellt von eurem repo, aber soweit ich das beurteilen kann sind keine strukturen oder implementierungen von Problemen, die beide Teams in code gelöst haben rübergewandert.
