### ISSUE TITLE
Fixing the travis build

### ISSUE THREAD

**Issue by ghost** [ProPra16/programmierpraktikum-abschlussprojekt-zenamike#7]
Make it function again please, I'm branching my stuff in order to work probably.

**Comment by zeljkobekcic** [comment]
Please add the missing code, it is not possible to continue work on the project due this mishap until you fix this.

![vivaldi_2016-07-08_18-26-20](https://cloud.githubusercontent.com/assets/10684523/16694290/b70445d4-4539-11e6-8f66-25b294ac7ade.png)

![vivaldi_2016-07-08_18-27-06](https://cloud.githubusercontent.com/assets/10684523/16694299/c4a3af2c-4539-11e6-9e6d-24cca2bed3a8.png)

![vivaldi_2016-07-08_18-27-40](https://cloud.githubusercontent.com/assets/10684523/16694303/c89509c8-4539-11e6-9cc8-0c78d8607837.png)

![vivaldi_2016-07-08_18-27-56](https://cloud.githubusercontent.com/assets/10684523/16694304/cbb28086-4539-11e6-96c5-1b8e7b69b9ff.png)

**Comment by zeljkobekcic** [comment]
Since the Travis CI build works (because of the hotfix which solves it (push by @nafoe) ) will this issue be closed.
