### ISSUE TITLE
What do we need for a release?

### ISSUE THREAD

**Issue by ghost** [ProPra16/programmierpraktikum-abschlussprojekt-zenamike#8]
What do we need for a release? Please brainstorm and comment.

**Comment by zeljkobekcic** [comment]
What do you think?
Just finish you part and everything is fine.

**Comment by ghost** [comment]
I don't think it's that easy.

**Comment by zeljkobekcic** [comment]
@nafoe 
@shaman78

**Comment by shaman78** [comment]
sugar spice and everything nice
